name: Build and Run C Program

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GCC
        run: sudo apt update && sudo apt install -y gcc

      - name: Compile C program
        run: gcc -o output main.c

      - name: Run the program
        run: ./output
